SELECT * FROM document
SELECT * FROM charge
SELECT * FROM administrator
SELECT * FROM account
SELECT * FROM person
SELECT * FROM usuario
SELECT * FROM instructor
SELECT * FROM schedule
SELECT * FROM consumer
SELECT * FROM type
SELECT * FROM requirement
SELECT * FROM ability
SELECT * FROM benefit
SELECT * FROM product
SELECT * FROM ability_product
SELECT * FROM consumer_product
SELECT * FROM requirement_product
SELECT * FROM benefit_product
SELECT * FROM pack
SELECT * FROM category
SELECT * FROM course
SELECT * FROM semester
SELECT * FROM topic
SELECT * FROM subtopic
SELECT * FROM shopping_cart
SELECT * FROM shopping_cart_detail
SELECT * FROM payment_method
SELECT * FROM orden
SELECT * FROM order_detail